import {RivenStat} from '../model/riven-stat.model';
import {WeaponTypes} from './weapon-type.values';

export const RivenStats: RivenStat[] = [
  {name: 'Ammo Maximum', prefix: 'Ampi', suffix: 'Bin', restrict: WeaponTypes.Melee},
  {name: 'Damage vs. Corpus', prefix: 'Manti', suffix: 'Tron'},
  {name: 'Damage vs. Grineer', prefix: 'Argi', suffix: 'Con'},
  {name: 'Damage vs. Infested', prefix: 'Pura', suffix: 'Ada'},
  {name: 'Cold Damage', prefix: 'Geli', suffix: 'Do'},
  {name: 'Channeling Damage', prefix: 'Tori', suffix: 'Bo', restrict: WeaponTypes.Melee},
  {name: 'Channeling Efficiency', prefix: 'Uti', suffix: 'Tia', restrict: WeaponTypes.Melee},
  {name: 'Combo Duration', prefix: 'Tempi', suffix: 'Nem', restrict: WeaponTypes.Ranged},
  {name: 'Critical Chance', prefix: 'Crita', suffix: 'Cron'},
  {name: 'Critical Chance on Slide Attack', prefix: 'Pleci', suffix: 'Nent', restrict: WeaponTypes.Melee},
  {name: 'Critical Damage', prefix: 'Acri', suffix: 'Tis'},
  {name: 'Base Damage / Melee Damage', prefix: 'Visi', suffix: 'Ata'},
  {name: 'Electric Damage', prefix: 'Vexi', suffix: 'Tio'},
  {name: 'Heat Damage', prefix: 'Igni', suffix: 'Pha'},
  {name: 'Finisher Damage', prefix: 'Exi', suffix: 'Cta', restrict: WeaponTypes.Melee},
  {name: 'Fire Rate / Attack Speed', prefix: 'Croni', suffix: 'Dra'},
  {name: 'Flight Speed', prefix: 'Conci', suffix: 'Nak', restrict: WeaponTypes.Ranged},
  {name: 'Impact Damage', prefix: 'Magna', suffix: 'Ton'},
  {name: 'Magazine Capacity', prefix: 'Arma', suffix: 'Tin', restrict: WeaponTypes.Ranged},
  {name: 'Multishot', prefix: 'Sati', suffix: 'Can', restrict: WeaponTypes.Ranged},
  {name: 'Toxin Damage', prefix: 'Toxi', suffix: 'Tox'},
  {name: 'Punch Through', prefix: 'Lexi', suffix: 'Nok', restrict: WeaponTypes.Ranged},
  {name: 'Puncture Damage', prefix: 'Insi', suffix: 'Cak'},
  {name: 'Reload Speed', prefix: 'Feva', suffix: 'Tak', restrict: WeaponTypes.Ranged},
  {name: 'Range', prefix: 'Locti', suffix: 'Tor', restrict: WeaponTypes.Melee},
  {name: 'Slash Damage', prefix: 'Sci', suffix: 'Sus'},
  {name: 'Status Chance', prefix: 'Hexa', suffix: 'Dex'},
  {name: 'Status Duration', prefix: 'Deci', suffix: 'Des'},
  {name: 'Recoil', prefix: 'Zeti', suffix: 'Mag', restrict: WeaponTypes.Ranged},
  {name: 'Zoom', prefix: 'Hera', suffix: 'Lis', restrict: WeaponTypes.Ranged},
];
